# Site settings
title: Restaurant Recommendation
email: orlando4@illinois.edu
description: Let us pick where you should go to dinner!
github_username: korlan1=01

#Build Settings (will effect whole website)
theme: jekyll-theme-leap-day
markdown: kramdown

